### ISSUE TITLE
authorization.create_token_response() returns a bad Response

### ISSUE THREAD

**Issue by pksec** [lepture/authlib#136]
**Error : AttributeError: 'Response' object has no attribute 'header' / 'status_code'/ 'content'**

I was trying to understand what authorization.create_token_response() returns in the example https://github.com/authlib/example-oauth2-server/blob/master/website/routes.py. So I created some logging statement as below:

```
oauthtoken = authorization.create_token_response()
app.logger.debug('oauthResponse type:{}'.format(type(oauthResponse)))
    app.logger.debug('oauth create token type:{} \n status code:{} \n header:{} \n content:{}'.format(
        type(oauthResponse),
        oauthResponse.status_code,
        oauthResponse.header,
        oauthResponse.content
    ))
```
I get the following response:

```
2019-06-21 22:00:19 routes.py DEBUG oauthResponse type:<class 'flask.wrappers.Response'>

2019-06-21 22:00:19 _internal.py INFO _log (122) 127.0.0.1 - - [21/Jun/2019 22:00:19] "POST /oauth/token HTTP/1.1" 500 -
Traceback (most recent call last):
...
  File "/home/xx/virtualenvs/xxx-n_KOMqPA/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xx/website/routes.py", line 216, in issue_token
    jwttoken = create_JWT_token (oauthtoken)
  File "/home/xx/website/routes.py", line 203, in xxx
    oauthResponse.header,
AttributeError: 'Response' object has no attribute 'header'
```
I traced the code back to authlib.oauth2.rfc6749.grants.authorization_code.py, still couldn't figure out why this error is happening ? what am I doing wrong? or is it an issue?

```
    def create_token_response(self):
        """If the access token request is valid and authorized, the
        authorization server issues an access token and optional refresh
        token as described in Section 5.1.  If the request client
        authentication failed or is invalid, the authorization server returns
        an error response as described in Section 5.2. Per `Section 4.1.4`_.

        An example successful response:

        .. code-block:: http

            HTTP/1.1 200 OK
            Content-Type: application/json
            Cache-Control: no-store
            Pragma: no-cache

            {
                "access_token":"2YotnFZFEjr1zCsicMWpAA",
                "token_type":"example",
                "expires_in":3600,
                "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA",
                "example_parameter":"example_value"
            }

        :returns: (status_code, body, headers)

        .. _`Section 4.1.4`: https://tools.ietf.org/html/rfc6749#section-4.1.4
        """
...
        return 200, token, self.TOKEN_RESPONSE_HEADER
```

**Comment by lepture** [comment]
`create_token_response` returns a `flask.Response` instance.
