### ISSUE TITLE
Error in “authorize_redirect(redirect_uri)” in Flask Client when running on cloud

### ISSUE THREAD

**Issue by MGafitescu** [lepture/authlib#137]
I'm using the Flask Client (authlib.flask.client) of authlib for OAuth with Flickr. On my machine, it works perfectly, but when running both on Heroku and Cloud Run (GCP) I encounter an error in the authorize_redirect method. Both my login and authorize methods are exactly as described in the Flask Client documentation.

The code I'm using and the error:

```
@app.route("/login")
def login():
    redirect_uri = url_for('authorize', _external=True)
    return oauth.flickr.authorize_redirect(redirect_uri)


@app.route('/authorize')
def authorize():
    token = oauth.flickr.authorize_access_token()
    redirect_url = "http://localhost:4200/#/login/"
    redirect_url = redirect_url + session.get("current_user", "")
    return redirect(redirect_url) 


Traceback (most recent call last): 
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app response = self.full_dispatch_request() 
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) 
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception reraise(exc_type, exc_value, tb) 
File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise raise value 
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request rv = self.dispatch_request() 
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) 
File "/app/main.py", line 130, in login return oauth.flickr.authorize_redirect(redirect_uri) 
File "/usr/local/lib/python3.7/site-packages/authlib/flask/client/oauth.py", line 244, in authorize_redirect **kwargs) 
File "/usr/local/lib/python3.7/site-packages/authlib/client/client.py", line 122, in generate_authorize_redirect with self._get_session() as session: 
File "/usr/local/lib/python3.7/site-packages/authlib/client/client.py", line 181, in _get_session **self.client_kwargs 
TypeError: type object argument after ** must be a mapping, not str
 ```

I tried using the name of the parameter too, as `return oauth.flickr.authorize_redirect(redirect_uri=redirect_uri)`, but I'm still getting the same error.

**Comment by lepture** [comment]
According to the error stack. Your `client_kwargs` is a str. Please check your code, make sure `client_kwargs` is a mapping.

**Comment by MGafitescu** [comment]
Thanks, I understood what I was doing wrong.
