### ISSUE TITLE
Error for httpx.AsyncClient due to drop of sync support

### ISSUE THREAD

**Issue by rostikL** [lepture/authlib#171]
**Describe the bug**

In the `0.8.0` release of httpx the sync support was dropped and some classes have been removed:
`AsyncClient, AsyncRequest, AsyncResponse` and moved to `Client, Request, Response`. Here some more information: [Commit](https://github.com/encode/httpx/commit/00e150f6a5f8d295faeadc34cfe53de254b3f264) / [Discussion](https://github.com/encode/httpx/issues/522)

I tried using the starlette_client and came across the error below.
Using authlib with httpx==0.7.8 works. 

I also made some changes here:  
- https://github.com/rostikL/authlib/commit/74d89654a048f75d1e92ef957318dd333f90877a
This works with the starlette_client, but I am not sure what effect it has on other integrations.

Anyway, wanted to share in case someone has the same error. 

**Error Stacks**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/api/app/__main__.py", line 1, in <module>
    from api.app.main import main
  File "/data/api/app/main.py", line 11, in <module>
    from api.app.starlette_app import app as starlette_app
  File "/data/api/app/starlette_app.py", line 8, in <module>
    from api.rest.v1.routers import api_v1_router
  File "/data/api/rest/v1/routers.py", line 8, in <module>
    from api.rest.v1.oauth import oauth
  File "/data/api/rest/v1/oauth/oauth.py", line 4, in <module>
    from authlib.integrations.starlette_client import OAuth
  File "/usr/local/lib/python3.7/site-packages/authlib/integrations/starlette_client/__init__.py", line 3, in <module>
    from .oauth_registry import OAuth as OAuth
  File "/usr/local/lib/python3.7/site-packages/authlib/integrations/starlette_client/oauth_registry.py", line 1, in <module>
    from .remote_app import RemoteApp
  File "/usr/local/lib/python3.7/site-packages/authlib/integrations/starlette_client/remote_app.py", line 2, in <module>
    from ..asgi_client import AsyncBaseApp
  File "/usr/local/lib/python3.7/site-packages/authlib/integrations/asgi_client/__init__.py", line 1, in <module>
    from .oauth_registry import OAuth
  File "/usr/local/lib/python3.7/site-packages/authlib/integrations/asgi_client/oauth_registry.py", line 2, in <module>
    from ..httpx_client import AsyncOAuth1Client, AsyncOAuth2Client
  File "/usr/local/lib/python3.7/site-packages/authlib/integrations/httpx_client/__init__.py", line 9, in <module>
    from .oauth1_client import OAuth1Auth, OAuth1Client, AsyncOAuth1Client
  File "/usr/local/lib/python3.7/site-packages/authlib/integrations/httpx_client/oauth1_client.py", line 2, in <module>
    from httpx import Client, AsyncClient
ImportError: cannot import name 'AsyncClient' from 'httpx' (/usr/local/lib/python3.7/site-packages/httpx/__init__.py)
```

**To Reproduce**

Execute:
https://github.com/authlib/demo-oauth-client/tree/master/starlette-google-login

**Comment by lepture** [comment]
@rostikL thanks for letting me know. Can you send your changes as a PR?

**Comment by rostikL** [comment]
@lepture Sure, created a PR. 

Regarding the `AssertionClient` The sync one can be removed and the other needs to be renamed to just `AssertionClient` if I am not mistaken.
