### ISSUE TITLE
Authlib does not correctly work with httpx middleware

### ISSUE THREAD

**Issue by kkinder** [lepture/authlib#175]
**Describe the bug**

**Error Stacks**

```
Traceback (most recent call last):
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/fastapi/routing.py", line 127, in app
    raw_response = await dependant.call(**values)
  File "./proj/apps/auth/api.py", line 77, in callback_oauth
    token = await current_oauth.authorize_access_token(request, redirect_uri=redirect_uri)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/src/authlib/authlib/integrations/starlette_client/remote_app.py", line 39, in authorize_access_token
    return await self.fetch_access_token(**params)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/src/authlib/authlib/integrations/asgi_client/base_app.py", line 104, in fetch_access_token
    token = await client.fetch_token(token_endpoint, **kwargs)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/src/authlib/authlib/integrations/httpx_client/oauth2_client.py", line 105, in _fetch_token
    resp = await self.post(
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/httpx/client.py", line 772, in post
    return await self.request(
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/src/authlib/authlib/integrations/httpx_client/oauth2_client.py", line 86, in request
    return await super(AsyncOAuth2Client, self).request(
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/httpx/client.py", line 259, in request
    response = await self.send(
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/httpx/client.py", line 403, in send
    response = await self.send_handling_redirects(
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/httpx/client.py", line 465, in send_handling_redirects
    response = await self.send_handling_auth(
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/httpx/client.py", line 589, in send_handling_auth
    request = next(auth_flow)
  File "/home/ken/.local/share/virtualenvs/testproj-lMPjJ55e/lib/python3.8/site-packages/httpx/auth.py", line 62, in __call__
    yield self.func(request)
TypeError: __call__() missing 1 required positional argument: 'get_response'
```

**To Reproduce**

1. Install Starlette/FastAPI
2. Use the current github version of authlib
3. Attempt to call authorize_access_token()

**Expected behavior**

It should work.

**Environment:**

 - OS: Ubuntu 18.04
 - Python Version: 3.8
 - Authlib Version: Current master branch

**Additional context**

Why this is happening is pretty obvious when you look at the code. Here's what httpx is doing:

```
class FunctionAuth(Auth):
    """
    Allows the 'auth' argument to be passed as a simple callable function,
    that takes the request, and returns a new, modified request.
    """

    def __init__(self, func: typing.Callable[[Request], Request]) -> None:
        self.func = func

    def __call__(self, request: Request) -> AuthFlow:
        yield self.func(request)
```

Notice it's calling self.func(request).

Here's the class it's calling __call__ on:

```
class OAuth2ClientAuth(Middleware, ClientAuth):
    async def __call__(
        self, request: Request, get_response: typing.Callable
    ) -> Response:
        return await auth_call(self, request, get_response)
```

get_response is not passed.

**Comment by ekalosak** [comment]
+1, I'm encountering the same bug on `macOS Mojave`

**Comment by ekalosak** [comment]
For the meantime @kkinder it looks like https://github.com/simonw/datasette-auth-github is the favored[1] alternative.

1. https://www.starlette.io/middleware/#datasette-auth-github

**Comment by lepture** [comment]
fixed in master
