### ISSUE TITLE
broken with httpx 0.10

### ISSUE THREAD

**Issue by kesavkolla** [lepture/authlib#178]
**Describe the bug**

authlib uses old classes of httpx.  New version of httpx 0.10 removed `AsyncRequest` `AsyncResponse` and also there's no middleware.

**Environment:**

 - OS: Linux
 - Python Version: 3.7
 - Authlib Version: 0.13

**Comment by romaia** [comment]
Just stumbled upon this issue and had to go back all the way to 0.7.8 to make it work.

0.8.0 is already failing with `ImportError: cannot import name 'AsyncClient' from 'httpx'`

**Comment by lepture** [comment]
It is already fixed in https://github.com/lepture/authlib/commit/c88ea7fe999a39e6da265f5ae012cab386538eaa

Not released yet.

**Comment by kesavkolla** [comment]
Still getting error

```
asyncio.run(client.fetch_token(token_endpoint))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/kesav/.virtualenvs/keycloak/lib/python3.7/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 107, in _fetch_token
    auth=auth, **kwargs)
  File "/home/kesav/.virtualenvs/keycloak/lib/python3.7/site-packages/httpx/client.py", line 761, in post
    trust_env=trust_env,
  File "/home/kesav/.virtualenvs/keycloak/lib/python3.7/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 87, in request
    method, url, auth=auth, **kwargs)
  File "/home/kesav/.virtualenvs/keycloak/lib/python3.7/site-packages/httpx/client.py", line 268, in request
    timeout=timeout,
  File "/home/kesav/.virtualenvs/keycloak/lib/python3.7/site-packages/httpx/client.py", line 402, in send
    request, auth=auth, timeout=timeout, allow_redirects=allow_redirects,
  File "/home/kesav/.virtualenvs/keycloak/lib/python3.7/site-packages/httpx/client.py", line 454, in send_handling_redirects
    request, auth=auth, timeout=timeout,
  File "/home/kesav/.virtualenvs/keycloak/lib/python3.7/site-packages/httpx/client.py", line 572, in send_handling_auth
    request = next(auth_flow)
  File "/home/kesav/.virtualenvs/keycloak/lib/python3.7/site-packages/httpx/auth.py", line 62, in __call__
    yield self.func(request)
TypeError: __call__() missing 1 required positional argument: 'get_response'
```

**Comment by lepture** [comment]
oh, httpx broken change again.

**Comment by lepture** [comment]
cc @tomchristie @florimondmanca

I've checked httpx 0.10 code, but I can't find any way to read **request** body in auth `__call__`.  Can you provide a way to read request content so that I can make a signature in auth `__call__`.

**Comment by kesavkolla** [comment]
@lepture httpx folks has introduced new auth mechanism in 0.11.  I think that can be added into authlib

**Comment by kofalt** [comment]
Just chiming in that I am also having this issue. The httpx's readme strongly encourages pinning due to API changes, so my guess is that authlib should probably do that until they have a 1.0 release.

Workaround: as per @romaia's comment, this appears to work:

```
pipenv install httpx==0.7.8
```

**Comment by lepture** [comment]
fixed in master
