### ISSUE TITLE
JWT validation of exp claim doesn't work if exp is 0

### ISSUE THREAD

**Issue by mivade** [lepture/authlib#179]
**Describe the bug**

Validation fails when the `exp` claim is 0.

**To Reproduce**

A minimal example to reproduce the behavior:

```
>>> from authlib.jose import JWTClaims
>>> claims = JWTClaims({"exp": 0}, {"alg": "HS256"})
>>> claims.validate()
>>> 
```

**Expected behavior**

What we should see is what we see with a positive value:

```
>>> claims = JWTClaims({"exp": 1}, {"alg": "HS256"})
>>> claims.validate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../python3.7/site-packages/authlib/jose/rfc7519/claims.py", line 98, in validate
    self.validate_exp(now, leeway)
  File "/.../python3.7/site-packages/authlib/jose/rfc7519/claims.py", line 171, in validate_exp
    raise ExpiredTokenError()
authlib.jose.errors.ExpiredTokenError: expired_token: The token is expired
```

**Environment:**

 - OS: macOS
 - Python Version: 3.7.5
 - Authlib Version: 0.13

**Comment by mivade** [comment]
Note I also see the expected `ExpiredTokenError` if I set `exp` to a negative value such as `-1`.

**Comment by lepture** [comment]
fixed
