### ISSUE TITLE
Google login with Flask: authorize_redirect - TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Jupiops** [lepture/authlib#271]
**Describe the bug**

authorize_redirect not working for Google login with Flask

**Error Stacks**

```
Traceback (most recent call last):
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\app\routes.py", line 19, in login
    return oauth.google.authorize_redirect(redirect_uri)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\authlib\integrations\flask_client\remote_app.py", line 58, in authorize_redirect
    rv = self.create_authorization_url(redirect_uri, **kwargs)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\authlib\integrations\base_client\remote_app.py", line 75, in create_authorization_url
    client, authorization_endpoint, **kwargs)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\authlib\integrations\base_client\base_app.py", line 186, in _create_oauth2_authorization_url
    authorization_endpoint, **kwargs)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\authlib\oauth2\client.py", line 154, in create_authorization_url
    state=state, **kwargs)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\authlib\oauth2\rfc6749\parameters.py", line 66, in prepare_grant_uri
    return add_params_to_uri(uri, params)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\authlib\common\urls.py", line 115, in add_params_to_uri
    query = add_params_to_qs(query, params)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\authlib\common\urls.py", line 106, in add_params_to_qs
    return url_encode(qs)
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\authlib\common\urls.py", line 44, in url_encode
    encoded.append((to_bytes(k), to_bytes(v)))
  File "C:\Users\Jupio\PycharmProjects\FlaskApp\venv\lib\site-packages\authlib\common\encoding.py", line 27, in to_bytes
    return byte_type(x)
TypeError: 'str' object cannot be interpreted as an integer
```

**To Reproduce**
```
@app.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    redirect_uri = url_for('authorize', _external=True)
    return oauth.google.authorize_redirect(redirect_uri)
```
**Expected behavior**

Should redirect to google login page

**Environment:**

 - OS:
 - Python Version: 3.7
 - Authlib Version: 0.14.3

**Comment by Jupiops** [comment]
a comma in the wrong place was what broke my neck

**Comment by s2t2** [comment]
how did you fix?

**Comment by s2t2** [comment]
We are experiencing this issue. Wrapping the url in a `str()` conversion, as suggested here https://stackoverflow.com/a/75918249/670433, does not work.

```py
def my_route():
    redirect_uri = url_for("auth_routes.google_oauth_callback", _external=True) 
    return oauth.google.authorize_redirect(redirect_uri)
```
