### ISSUE TITLE
OAuth2Client._refresh_token() error handling

### ISSUE THREAD

**Issue by james-emerton** [lepture/authlib#281]
**Describe the bug**

When a token is refreshed via `OAuth2Client._refresh_token()` the response from the token endpoint is not checked for errors.

**Error Stacks**

```
Traceback (most recent call last):
<snip>
  File "C:\Users\James\dev\spire\.venv\lib\site-packages\authlib\integrations\requests_client\oauth2_session.py", line 34, in __call__
    self.ensure_active_token()
  File "C:\Users\James\dev\spire\.venv\lib\site-packages\authlib\integrations\requests_client\oauth2_session.py", line 24, in ensure_active_token
    client.refresh_token(url, refresh_token=refresh_token)
  File "C:\Users\James\dev\spire\.venv\lib\site-packages\authlib\oauth2\client.py", line 264, in refresh_token
    auth=auth, **session_kwargs)
  File "C:\Users\James\dev\spire\.venv\lib\site-packages\authlib\oauth2\client.py", line 280, in _refresh_token
    self.update_token(self.token, refresh_token=refresh_token)
  File "c:\users\james\dev\spire\spire-server\src\spired\provider\oauth.py", line 60, in update_token
    record.from_token(token)
  File "c:\users\james\dev\spire\spire-server\src\spired\provider\models.py", line 85, in from_token
    raise ValueError('Invalid token')
ValueError: Invalid token
```

**To Reproduce**

 1. Provide an invalid `refresh_token` and set `expires_at` in the past to force a refresh.
 2. Make a request and see that the `update_token` function is called with invalid token data.

**Expected behavior**

`OAuth2Client._refresh_token()` should check for error conditions and raise the appropriate exception.

**Environment:**

 - OS: Windows 10 2004
 - Python Version: 3.7.5
 - Authlib Version: 0.14.3

**Additional context**

I've worked around this by adding a `refresh_token_response` hook and calling `raise_for_status()` on the response.

**Comment by lepture** [comment]
What is the response from token endpoint when refreshing the token? According to our code:

```python
    def parse_response_token(self, token):
        if 'error' not in token:
            self.token = token
            return self.token

        error = token['error']
        description = token.get('error_description', error)
        self.handle_error(error, description)
```

If the returned token response is an error, it should raise the error inside refresh token method.

**Comment by lepture** [comment]
If the returned response is not in the standard format, it is correct for you to add `refresh_token_response` hook.
