### ISSUE TITLE
Failure to extend the password flow with an id_token

### ISSUE THREAD

**Issue by jackburridge** [lepture/authlib#301]
**Describe the bug**

I've attempted to extend the password flow so it also returns a JWT, instead of returning a token the server returns with an error.

**Error Stacks**

```
Traceback (most recent call last):
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/****/Dev/example-oidc-server/website/routes.py", line 97, in issue_token
    return authorization.create_token_response()
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/authlib/oauth2/rfc6749/authorization_server.py", line 216, in create_token_response
    args = grant.create_token_response()
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/authlib/oauth2/rfc6749/grants/resource_owner_password_credentials.py", line 145, in create_token_response
    self.execute_hook('process_token', token=token)
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/authlib/oauth2/rfc6749/grants/base.py", line 88, in execute_hook
    hook(self, *args, **kwargs)
  File "/home/****/Dev/example-oidc-server/venv/lib/python3.8/site-packages/authlib/oidc/core/grants/code.py", line 116, in process_token
    config['nonce'] = credential.get_nonce()
AttributeError: 'NoneType' object has no attribute 'get_nonce'
```

**To Reproduce**

Using a combination of the [example-oauth2-server](https://github.com/authlib/example-oauth2-server) and [example-oidc-server](https://github.com/authlib/example-oidc-server) extend the authorisation server so that the `PasswordGrant` uses the `OpenIDCode` extension.
```python
authorization.register_grant(PasswordGrant, [
    OpenIDCode(require_nonce=False),
])
```

**Expected behavior**

When using the password flow you should also get an `id_token`

**Environment:**

 - OS: `Linux pop-os 5.8.0-7630-generic #32~1605108806~20.10~7e52b13-Ubuntu SMP Wed Nov 11 19:10:30 UTC  x86_64 GNU/Linux`
 - Python Version: `3.8.6`
 - Authlib Version: `0.13`

**Comment by lepture** [comment]
@jackburridge currently `OpenIDCode` is only available for authorization code flow. I'm working on a generic `OpenIDToken` extension: https://github.com/lepture/authlib/blob/master/authlib/oidc/core/grants/code.py#L22

For now, it doesn't support `password` flow either. I'll make it available in v1.
