### ISSUE TITLE
authorize_access_token() doesn't add client_secret to query with GET request

### ISSUE THREAD

**Issue by Ander813** [lepture/authlib#303]
When you send GET request to get access token client_secret is not added to query.

Here is some prints from methods:

request method: GET <authlib.integrations.httpx_client.oauth2_client.OAuth2ClientAuth object at 0x00000203BB662B80> SOME_CLIENT_SECRET
send method: <authlib.integrations.httpx_client.oauth2_client.OAuth2ClientAuth object at 0x00000203BB662B80> SOME_CLIENT_SECRET
_send_handling_auth method: response <Response [401 Unauthorized]> b'{"error":"invalid_client","error_description":"client_secret is undefined"}'
As you can see everything fine with Auth object and client_secret is in it, but something wrong with _send_handling_auth

Full error callback:

client_secret <authlib.integrations.httpx_client.oauth2_client.OAuth2ClientAuth object at 0x0000020867A03B80> SOME_CLIENT_SECRET
Traceback (most recent call last):
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\fastapi\applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\fastapi\routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\fastapi\routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File ".\src\app\auth\routes.py", line 47, in vk_auth
    token = await oauth.vk.authorize_access_token(request, method='GET')
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\integrations\starlette_client\integration.py", line 64, in authorize_access_token
    return await self.fetch_access_token(**params)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\integrations\base_client\async_app.py", line 105, in fetch_access_token
    token = await client.fetch_token(token_endpoint, **kwargs)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\integrations\httpx_client\oauth2_client.py", line 133, in _fetch_token
    return self.parse_response_token(resp.json())
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\oauth2\client.py", line 380, in parse_response_token
    self.handle_error(error, description)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\integrations\httpx_client\oauth2_client.py", line 82, in handle_error
    raise OAuthError(error_type, error_description)
authlib.integrations.base_client.errors.OAuthError: invalid_client: client_secret is undefined
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\fastapi\applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\fastapi\routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\fastapi\routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File ".\src\app\auth\routes.py", line 47, in vk_auth
    token = await oauth.vk.authorize_access_token(request, method='GET')
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\integrations\starlette_client\integration.py", line 64, in authorize_access_token
    return await self.fetch_access_token(**params)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\integrations\base_client\async_app.py", line 105, in fetch_access_token
    token = await client.fetch_token(token_endpoint, **kwargs)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\integrations\httpx_client\oauth2_client.py", line 133, in _fetch_token
    return self.parse_response_token(resp.json())
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\oauth2\client.py", line 380, in parse_response_token
    self.handle_error(error, description)
  File "c:\users\ander\appdata\local\programs\python\python39\lib\site-packages\authlib\integrations\httpx_client\oauth2_client.py", line 82, in handle_error
    raise OAuthError(error_type, error_description)
authlib.integrations.base_client.errors.OAuthError: invalid_client: client_secret is undefined

**To Reproduce**
```
oauth.register(
    name='vk',
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    authorize_url='https://oauth.vk.com/authorize',
    access_token_url='https://oauth.vk.com/access_token',
)

@router.get('/login/vk')
async def vk_login(request: Request):
    redirect_uri = request.url_for('vk_auth')
    return await oauth.vk.authorize_redirect(request, redirect_uri)


@router.get('/')
async def vk_auth(request: Request):
    token = await oauth.vk.authorize_access_token(request, method='GET')  <-  error here
```

**Expected behavior**
await oauth.vk.authorize_access_token(request, method='GET') makes request with url like https://some-site.com/access-token?client_id=id&client_secret=secret&redirect_uri=uri&code=code&state=state

**Environment:**
 - OS: Windows 10
 - Python Version: 3.9
 - Authlib Version: 0.15.2
- starlette: 0.13.6
- fastapi: 0.61.2

**Comment by lepture** [comment]
This `GET` access token is not standard OAuth. To get what you want, you need to use `compliance_fix`, check:

https://docs.authlib.org/en/latest/client/frameworks.html#compliance-fix-for-oauth-2-0

**Comment by Ander813** [comment]
The problem with compliance_fix is that this method adds hook to TokenAuth class, but when you call .authorize_access_token, ClientAuth class is used.
ClientAuth has DEFAULT_AUTH_METHODS = {
        'client_secret_basic': encode_client_secret_basic,
        'client_secret_post': encode_client_secret_post,
        'none': encode_none,
    }
so I set token_endpoint_auth_method='none' in .register() and also changed encode_none func:
```
def encode_none(client, method, uri, headers, body):
    if method == 'GET':
        uri = add_params_to_uri(uri, [('client_id', client.client_id),
                                      ('client_secret', client.client_secret)]) <-- added this
        return uri, headers, body
    body = add_params_to_qs(body, [('client_id', client.client_id)])
    if 'Content-Length' in headers:
        headers['Content-Length'] = str(len(body))
    return uri, headers, body
```
And now when I use oauth.vk.authorize_access_token(request, method='GET') everything works fine, and i get my access_token from vk.

Probably you could suggest me a better solution for my problem without changing the source files.

**Comment by lepture** [comment]
You can register a new auth method, e.g. name it `client_secret_get`.
