### ISSUE TITLE
Cannot get token with refresh token when using client-authentication and client_auth_method is set to ClientSecretJWT

### ISSUE THREAD

**Issue by LeoQuote** [lepture/authlib#332]
**Describe the bug**

I'm using keycloak as oidc provider, I used the example code to get a Oauth2session 

```
from authlib.integrations.requests_client import OAuth2Session
from authlib.oauth2.rfc7523 import ClientSecretJWT

session = OAuth2Session(client_id, client_secret)
session.register_client_auth_method(ClientSecretJWT(token_endpoint))
token = session.fetch_token(token_endpoint)

# when the token is expired , I use the access token to refresh token
token = session.refresh_token(token_endpoint)
```

I think it's because session are not using correct client_auth_method , I cannot see any parameter of `refresh_token` to set `client_auth_method `, I tried to `register_client_auth_method` but still no work. 

I debugged this process and found  session.metadata is an empty dict , maybe we can save the client_auth_method here

**Error Stacks**

```
session.refresh_token(client.token_endpoint)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\mycode\venv\lib\site-packages\authlib\oauth2\client.py", line 262, in refresh_token
    return self._refresh_token(
  File "D:\mycode\venv\lib\site-packages\authlib\oauth2\client.py", line 275, in _refresh_token
    token = self.parse_response_token(resp.json())
  File "D:\mycode\venv\lib\site-packages\authlib\oauth2\client.py", line 380, in parse_response_token
    self.handle_error(error, description)
  File "D:\mycode\venv\lib\site-packages\authlib\integrations\requests_client\oauth2_session.py", line 117, in handle_error
    raise OAuthError(error_type, error_description)
authlib.integrations.base_client.errors.OAuthError: invalid_client: Parameter client_assertion_type is missing
```

**To Reproduce**

A minimal example to reproduce the behavior:

**Expected behavior**

**Environment:**

 - OS: Windows 10
 - Python Version: Python 3.9.1
 - Authlib Version: Authlib==0.15.3

**Additional context**

**Comment by LeoQuote** [comment]
I checked my code and found that the problem is that I dumped access token as dict and saved it in a varible , then loaded back with token = xxx parameter, the auth method info was perhpas lost during, resulting a failure when refreshing token. closing this issue...
