### ISSUE TITLE
starlette client would raise Too much data for declared Content-Length error if token_endpoint_auth_method is set 

### ISSUE THREAD

**Issue by LeoQuote** [lepture/authlib#335]
**Describe the bug**

Starlette client raise exception when sending request to oidc provider. Seems that the token_endpoint_auth_method is the key to trigger this bug.

```
h11._util.LocalProtocolError: Too much data for declared Content-Length
```
**Error Stacks**

```
INFO:     127.0.0.1:55700 - "GET /auth/keycloak?state=pfZIr1oOLAUVgC0mnAnhuCpwLkwmOH&session_state=500d7b38-a6f2-45c8-a812-d1ad98902f2d&code=c28c181f-ed14-45cf-9831-d4e944ee894f.500d7b38-a6f2-45c8-a812-d1ad98902f2d.96855985-07d2-4e81-a715-62551556c73c HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\mycode\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\mycode\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "D:\mycode\venv\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "D:\mycode\venv\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\mycode\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "D:\mycode\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\mycode\venv\lib\site-packages\starlette\middleware\sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "D:\mycode\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "D:\mycode\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "D:\mycode\venv\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "D:\mycode\venv\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "D:\mycode\venv\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "D:\mycode\venv\lib\site-packages\fastapi\routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "D:\mycode\venv\lib\site-packages\fastapi\routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\mycode\examples\fastapi\main.py", line 35, in auth_via_keycloak
    token = await oauth.keycloak.authorize_access_token(request)
  File "D:\mycode\venv\lib\site-packages\authlib\integrations\starlette_client\integration.py", line 64, in authorize_access_token
    return await self.fetch_access_token(**params)
  File "D:\mycode\venv\lib\site-packages\authlib\integrations\base_client\async_app.py", line 105, in fetch_access_token
    token = await client.fetch_token(token_endpoint, **kwargs)
  File "D:\mycode\venv\lib\site-packages\authlib\integrations\httpx_client\oauth2_client.py", line 120, in _fetch_token
    resp = await self.post(
  File "D:\mycode\venv\lib\site-packages\httpx\_client.py", line 1624, in post
    return await self.request(
  File "D:\mycode\venv\lib\site-packages\authlib\integrations\httpx_client\oauth2_client.py", line 94, in request
    return await super(AsyncOAuth2Client, self).request(
  File "D:\mycode\venv\lib\site-packages\httpx\_client.py", line 1361, in request
    response = await self.send(
  File "D:\mycode\venv\lib\site-packages\httpx\_client.py", line 1396, in send
    response = await self._send_handling_auth(
  File "D:\mycode\venv\lib\site-packages\httpx\_client.py", line 1434, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\mycode\venv\lib\site-packages\httpx\_client.py", line 1466, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "D:\mycode\venv\lib\site-packages\httpx\_client.py", line 1492, in _send_single_request
    (status_code, headers, stream, ext) = await transport.arequest(
  File "D:\mycode\venv\lib\site-packages\httpx\_transports\default.py", line 169, in arequest
    return await self._pool.arequest(
  File "D:\mycode\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "D:\mycode\venv\lib\site-packages\httpcore\_async\connection.py", line 106, in arequest
    return await self.connection.arequest(method, url, headers, stream, ext)
  File "D:\mycode\venv\lib\site-packages\httpcore\_async\http11.py", line 66, in arequest
    await self._send_request_body(stream, timeout)
  File "D:\mycode\venv\lib\site-packages\httpcore\_async\http11.py", line 112, in _send_request_body
    await self._send_event(event, timeout)
  File "D:\mycode\venv\lib\site-packages\httpcore\_async\http11.py", line 123, in _send_event
    bytes_to_send = self.h11_state.send(event)
  File "D:\mycode\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "D:\mycode\venv\lib\site-packages\h11\_connection.py", line 501, in send_with_data_passthrough
    writer(event, data_list.append)
  File "D:\mycode\venv\lib\site-packages\h11\_writers.py", line 58, in __call__
    self.send_data(event.data, write)
  File "D:\mycode\venv\lib\site-packages\h11\_writers.py", line 78, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

**To Reproduce**

1. set up as the starlette example 
2. set oidc client auth method as signed jwt with client secret in keycloak admin
3. set `token_endpoint_auth_method=ClientSecretJWT()` when registering oauth client
4. visit localhost:8000/login as normal and redirected to oidc provider , then auth success in oidc provider and redirect back to /auth

**Expected behavior**

expect /auth return 200 and auth success

**Environment:**

 - OS: Windows 10
 - Python Version: 3.9
 - Authlib Version: 0.15.3

**Additional context**

full example here : https://gist.github.com/LeoQuote/f3aa47662df5026f46b5d92d88a5a3d2

**Comment by grofonn** [comment]
I have the same issue. It seems that the content-length header is already set before the auth method (the PrivateKeyJWT for me) adds data to the content.

**Comment by janwijbrand** [comment]
I have the same issue. I cowboyed up and applied commit https://github.com/lepture/authlib/commit/cfa15c00ba0175e515309d33e0cd347a15779994 to my install, but to no avail.

**Comment by janwijbrand** [comment]
Ah, if I add the same content-length header line in the `OAuth2ClientAuth`, the PrivateKeyJWT method wont fail on this error anymore! That would fix that situation too.

**Comment by lepture** [comment]
@janwijbrand thanks. I missed that one. I've fixed it in master code.
