### ISSUE TITLE
Error handling during token refresh

### ISSUE THREAD

**Issue by james-emerton** [lepture/authlib#338]
**Describe the bug**

If the IdP responds with an error during `refresh_token()`, a `JSONDecodeError` is raised rather than an HTTP or Authlib specific exception.

During the recent Auth0 outage, their endpoints were responding with a 502 error with a response body that was not JSON. This cause some outage in some of our systems which were designed to gracefully recover from server errors.

**Error Stacks**

```
Traceback (most recent call last):
  ...
  File "Build\Lib\site-packages\authlib\client\oauth2_session.py", line 105, in request
  File "Build\Lib\site-packages\requests\sessions.py", line 519, in request
  File "Build\Lib\site-packages\requests\sessions.py", line 462, in prepare_request
  File "Build\Lib\site-packages\requests\models.py", line 317, in prepare
  File "Build\Lib\site-packages\requests\models.py", line 548, in prepare_auth
  File "Build\Lib\site-packages\authlib\client\oauth2_session.py", line 26, in __call__
  File "Build\Lib\site-packages\authlib\oauth2\client_auth.py", line 101, in ensure_refresh_token
  File "Build\Lib\site-packages\authlib\oauth2\client.py", line 222, in refresh_token
  File "Build\Lib\site-packages\authlib\oauth2\client.py", line 233, in _refresh_token
  File "Build\Lib\site-packages\requests\models.py", line 897, in json
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\__init__.py", line 348, in loads
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\decoder.py", line 337, in decode
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**

Given an expired JWT and valid refresh token, arrange to have an IdP return a 5xx error with a non-JSON response body. Observe that a `JSONDecodeError` is raised.

**Expected behavior**

During `refresh_token()` (or any other request), if the response arrives with an invalid status code the `AuthlibHTTPError` should be raised.

**Environment:**

 - Python Version: 3.8.8
 - Authlib Version: 0.15.2

**Additional context**

I originally opened a very similar ticket as #281 in the context of an invalid refresh token that was ignoring a 4xx error from the server. It was rejected and I implemented error handling in a hook as a workaround, though I don't necessarily agree that Authlib should be ignoring the response status code in that case.

In this case, I feel quite strongly that Authlib should not be leaking errors from the underlying HTTP or JSON implementation.

I am happy to provide a PR to improve this behaviour and I'm open to suggestions about what specific errors should be raised under various circumstances. I feel there should be error handling for both HTTP and network errors.

**Comment by lepture** [comment]
```
File "Build\Lib\site-packages\authlib\client\oauth2_session.py", line 26, in __call__
```

It seems you are using the wrong Authlib version. In `Authlib Version: 0.15.2`, there is no `authlib.client` module. Please update to Authlib v0.15.3.
