### ISSUE TITLE
_HTTPException arguments error

### ISSUE THREAD

**Issue by Ndr6** [lepture/authlib#354]
**Describe the bug**
I am implementing OAuth2 authentication in my Flask project, and am encountering a problem when I try to access a protected route with an revoked token. The BearerTokenValidator throws an InvalidTokenError, but it is not catched by Werkzeug, which tells that there is an excess argument (see error stack)

I am not really sure whether this is a problem with my code, or if it is due to the fact that I use Werkzeug 2.0.1 which is fairly recent

Sorry if this is an error in my code, I tried to find what could break this but haven't been able to find the cause

**Error Stacks**

```
Traceback (most recent call last):
  File "/home/***/venv/lib/python3.9/site-packages/authlib/integrations/flask_oauth2/resource_protector.py", line 106, in decorated
    self.acquire_token(scope, operator)
  File "/home/***/venv/lib/python3.9/site-packages/authlib/integrations/flask_oauth2/resource_protector.py", line 79, in acquire_token
    token = self.validate_request(scope, request, operator)
  File "/home/***/venv/lib/python3.9/site-packages/authlib/oauth2/rfc6749/resource_protector.py", line 37, in validate_request
    return validator(token_string, scope, request, scope_operator)
  File "/home/***/venv/lib/python3.9/site-packages/authlib/oauth2/rfc6750/validator.py", line 96, in __call__
    raise InvalidTokenError(realm=self.realm)
authlib.oauth2.rfc6750.errors.InvalidTokenError: invalid_token:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/venv/lib/python3.9/site-packages/flask/app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/***/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "/home/***/venv/lib/python3.9/site-packages/authlib/integrations/flask_oauth2/resource_protector.py", line 112, in decorated
    self.raise_error_response(error)
  File "/home/***/venv/lib/python3.9/site-packages/authlib/integrations/flask_oauth2/resource_protector.py", line 62, in raise_error_response
    raise_http_exception(status, body, headers)
  File "/home/***/venv/lib/python3.9/site-packages/authlib/integrations/flask_oauth2/errors.py", line 20, in raise_http_exception
    raise _HTTPException(status, body, headers)
authlib.integrations.flask_oauth2.errors._HTTPException: 401 Unauthorized: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/venv/lib/python3.9/site-packages/flask/app.py", line 1718, in make_response
    rv = self.response_class.force_type(rv, request.environ)  # type: ignore  # noqa: B950
  File "/home/***/venv/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 263, in force_type
    response = Response(*run_wsgi_app(response, environ))
  File "/home/***/venv/lib/python3.9/site-packages/werkzeug/test.py", line 1229, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/home/***/venv/lib/python3.9/site-packages/werkzeug/exceptions.py", line 221, in __call__
    response = t.cast("WSGIResponse", self.get_response(environ))
  File "/home/***/venv/lib/python3.9/site-packages/werkzeug/exceptions.py", line 209, in get_response
    headers = self.get_headers(environ, scope)
TypeError: get_headers() takes from 1 to 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/venv/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/***/venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/***/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/***/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/***/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/***/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/***/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/***/venv/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    raise TypeError(
  File "/home/***/venv/lib/python3.9/site-packages/flask/app.py", line 1718, in make_response
    rv = self.response_class.force_type(rv, request.environ)  # type: ignore  # noqa: B950
  File "/home/***/venv/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 263, in force_type
    response = Response(*run_wsgi_app(response, environ))
  File "/home/***/venv/lib/python3.9/site-packages/werkzeug/test.py", line 1229, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/home/***/venv/lib/python3.9/site-packages/werkzeug/exceptions.py", line 221, in __call__
    response = t.cast("WSGIResponse", self.get_response(environ))
  File "/home/***/venv/lib/python3.9/site-packages/werkzeug/exceptions.py", line 209, in get_response
    headers = self.get_headers(environ, scope)
TypeError: get_headers() takes from 1 to 2 positional arguments but 3 were given
The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a _HTTPException.
```

**To Reproduce**

- Setup a OAuth2 resource server token validator
- Generate a valid token
- Revoke the token
- Send a restricted request, to cause an InvalidTokenError

**Expected behavior**

The exception should have been catched by Werkzeug or authlib ?

**Environment:**

 - OS: Ubuntu 21.04
 - Python Version: 3.9
 - Authlib Version: 0.15.4

**Comment by Ndr6** [comment]
Oh, sorry, this is a duplicate of #346
