### ISSUE TITLE
`AuthTypes` of httpx does not include `UnsetType`

### ISSUE THREAD

**Issue by jumpyapple** [lepture/authlib#357]
**Describe the bug**

From the discussion at https://github.com/encode/httpx/discussions/1697 by @Shivansh-007, the error is

`TypeError: Invalid "auth" argument: <httpx._config.UnsetType object at 0x7fbd7bcbc8e0>`

**Error Stacks**

Taken from the aforementioned discussion.

```
Save New Duplicate & Edit Just Text Twitter
Traceback (most recent call last):
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/shivansh/PythonProjects/voting-application-fastapi/app/main.py", line 66, in login
    return await oauth.google.authorize_redirect(request, redirect_uri)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/authlib/integrations/starlette_client/integration.py", line 52, in authorize_redirect
    rv = await self.create_authorization_url(redirect_uri, **kwargs)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/authlib/integrations/base_client/async_app.py", line 51, in create_authorization_url
    metadata = await self.load_server_metadata()
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/authlib/integrations/base_client/async_app.py", line 20, in load_server_metadata
    metadata = await self._fetch_server_metadata(self._server_metadata_url)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/authlib/integrations/base_client/async_app.py", line 204, in _fetch_server_metadata
    resp = await client.request('GET', url, withhold_token=True)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 94, in request
    return await super(AsyncOAuth2Client, self).request(
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1481, in request
    response = await self.send(
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1566, in send
    auth = self._build_request_auth(request, auth)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 433, in _build_request_auth
    self._auth if isinstance(auth, UseClientDefault) else self._build_auth(auth)
  File "/home/shivansh/.cache/pypoetry/virtualenvs/voting-application-fastapi-nxHNqp5f-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 425, in _build_auth
    raise TypeError(f'Invalid "auth" argument: {auth!r}')
```

**To Reproduce**

1. Setup the starlette google login from the source code at https://github.com/authlib/demo-oauth-client/blob/master/starlette-google-login with 
 - Authlib == 0.15.4
 - httpx == 0.18.2
2. Start the app and visit `/login`.

**Expected behavior**

The page is redirected to the Google login.

**Environment:**

 - OS: Linux 5.12.10-arch1-1
 - Python Version: 3.9.1 
 - Authlib Version: 0.15.4

**Additional context**

From https://github.com/encode/httpx/blob/master/httpx/_types.py the `AuthTypes` is declared as follows

```python
AuthTypes = Union[
    Tuple[Union[str, bytes], Union[str, bytes]],
    Callable[["Request"], "Request"],
    "Auth",
    None,
]
```
where there is no use of `UnsetType` (from https://github.com/encode/httpx/blob/master/httpx/_config.py#L37) anywhere.

However, this [commit](https://github.com/lepture/authlib/commit/b617595928c4e24b84aee5cc299ef0acf107dabe#diff-a76b0555f3b9e33dfc186fd581c4cf7a2a4e6082272232786a08d22de33c57ceR84) sets the default value to `UNSET` for `auth` parameter of the `request` function.

This `auth` is then passed to [`_build_auth`](https://github.com/encode/httpx/blob/master/httpx/_client.py#L415) where the type of the `auth` is said to be `AuthTypes`.

**Comment by jumpyapple** [comment]
hmm. Just saw that `UnsetType` was used in https://github.com/encode/httpx/blame/34ba0e14b0d588860e408e6e21ec729af5667f7f/httpx/_client.py#L288 before it get remove with `https/_types.py`

**Comment by ZhengRui** [comment]
I just had the same issue when trying out demos

https://github.com/authlib/demo-oauth-client/issues/14

**Comment by lepture** [comment]
fixed in master code.
