### ISSUE TITLE
on event.headers.raw_items : AttributeError: 'list' object has no attribute 'raw_items'

### ISSUE THREAD

**Issue by spock** [lepture/authlib#386]
_I have now solved the issue, posting to document and to save someone else lots of time. Solution is in the first comment below._

**Describe the bug**

When following the Facebook OAuth example (can't), Authlib versions 0.15.2-0.15.4 (with `httpx` pinned at 0.18.1) produces the stack trace (below) upon receiving an authentication callback from Facebook.

**Error Stacks**

```
8x.8x.23x.11x:0 - "GET /facebook_auth?code=A...Y&state=L..z HTTP/1.1" 500
[2021-09-21 17:18:03 +0000] [10] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 188, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 135, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 126, in facebook_auth
    token = await client.authorize_access_token(request)
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/starlette_client/integration.py", line 64, in authorize_access_token
    return await self.fetch_access_token(**params)
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/base_client/async_app.py", line 105, in fetch_access_token
    token = await client.fetch_token(token_endpoint, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 120, in _fetch_token
    resp = await self.post(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1746, in post
    return await self.request(
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 94, in request
    return await super(AsyncOAuth2Client, self).request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1425, in request
    response = await self.send(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1510, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1545, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1579, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1620, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 279, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.8/site-packages/httpcore/_async/connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "/usr/local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 128, in handle_async_request
    ) = await self._receive_response(timeout)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_async/http11.py", line 197, in _receive_response
    headers = event.headers.raw_items()
AttributeError: 'list' object has no attribute 'raw_items'
```

**To Reproduce**

Here's the function which handles auth callback from facebook and where the exception is triggered, on the `user = await ...` line:

```python
class FacebookAuthCBV:
    @router.get("/facebook_auth", name="facebook_auth")
    async def facebook_auth(self, request: Request):
        try:
            token = await oauth.facebook.authorize_access_token(request)
        except OAuthError as error:
            return HTMLResponse(f"<h1>{error.error}</h1>")
        user = await oauth.facebook.parse_id_token(request, token)
        request.session['user'] = dict(user)
        return JSONResponse(dict(user))
```

**Expected behavior**

We expected facebook login to work just like google login works - with the same versions, and with nearly identical code (save for `s/google/facebook/` changes.

**Environment:**

 - OS: Debian bullseye (Docker image tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim)
 - Python Version: 3.8
 - Authlib Version: 0.15.4

**Comment by spock** [comment]
For some reason, `parse_id_token` didn't work for us, but replacing this line
```python
    user = await oauth.facebook.parse_id_token(request, token)
```

with

```python
    resp = await oauth.facebook.get('me?fields=id,name,email,picture{url}', token=token)
    resp.raise_for_status()
    user = resp.json()
```
did fix the issue.

**Comment by lepture** [comment]
`.parse_id_token` is used to parse `id_token`, which is an OpenID connect thing. Facebook doesn't support OpenID connect.

**Comment by MilanRgm** [comment]
Does gitlab also not support openID connect? Because, I am also getting issue when I do `user = await gitlab.parse_id_token(request, token)`
