### ISSUE TITLE
Key Error: 'id_token' on Starlette

### ISSUE THREAD

**Issue by rushilsrivastava** [lepture/authlib#387]
**Describe the bug**

The Async OpenID integration does not work in the v1 builds.

**Error Stacks**

```Python
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 106, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 152, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 149, in _run_app
    return await callback()
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/./example/oauth/google/routes.py", line 32, in google_oauth
    user_info = await oauth.google.parse_id_token(request, token)
  File "/usr/local/lib/python3.9/site-packages/authlib/integrations/base_client/async_openid.py", line 59, in parse_id_token
    token['id_token'],
  File "/usr/local/lib/python3.9/site-packages/starlette/requests.py", line 68, in __getitem__
    return self.scope[key]
KeyError: 'id_token'
```

See additional error stack in https://github.com/authlib/demo-oauth-client/issues/17

**To Reproduce**

```
@app.get('/auth')
async def google_oauth(request: Request):
    token = await oauth.google.authorize_access_token(request)
    user_info = await oauth.google.parse_id_token(request, token)
```

See additional example in https://github.com/authlib/demo-oauth-client/issues/17

**Expected behavior**

As @sondrelg found, I think the problem is in the way that authlib is reading the nonce parameter via httpx which is causing the whole function to fail. This same function worked as is in the 0.15.2, but newer version of httpx did not work with it.

**Environment:**

 - OS: Ubuntu
 - Python Version: 3.9.5
 - Authlib Version: 1.0.0b1

**Comment by lepture** [comment]
@rushilsrivastava from my understanding, you don't need to parse_id_token manually.

https://github.com/lepture/authlib/blob/b8f7cc7b709a5222591ee7d56954b6e893696fa4/authlib/integrations/starlette_client/apps.py#L65-L70

There will be a `userinfo` in the token when `authorize_access_token`

**Comment by rushilsrivastava** [comment]
Yes, you are right. Sorry, this is not a bug in the code but in the documentation - should have taken a closer look there.

I think the documentation for 1.0.0 needs to be updated as well: https://docs.authlib.org/en/latest/client/starlette.html

**Comment by ahmedgaboelnaga** [comment]
I had the same problem, and I had no problem with this different method
 `    user_info = await oauth.google.userinfo(token=token)
`
