### ISSUE TITLE
[Flask] using automatic token refresh failed.

### ISSUE THREAD

**Issue by nebularazer** [lepture/authlib#44]
I am trying to automatically refresh tokens stored in a postgres db as json.
With this example Flask app:

``` python
from flask import Flask, jsonify
from authlib.flask.client import OAuth

app = Flask(__name__)
oauth = OAuth(app)

def fetch_token():
    log.info('fetch_token')
    return current_user.token

def update_token(token):
    log.info('update_token')
    current_user.token = token
    return token

oauth.register(
    'google',
    api_base_url='https://www.googleapis.com/',
    access_token_url='https://www.googleapis.com/oauth2/v4/token',
    authorize_url='https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&include_granted_scopes=true&login_hint=zalando&hd=*',
    refresh_token_url='https://www.googleapis.com/oauth2/v4/token',
    client_kwargs = {'scope': 'email profile'},
    fetch_token=fetch_token,
    update_token=update_token
)

@app.route('/')
def index():
    resp = oauth.google.get('/oauth2/v2/userinfo')
    data = resp.json()
    return jsonify(data)

@app.route('/login')
@login_required
def authorize():
    redirect_uri = url_for('.google', _external=True)
    return oauth.google.authorize_redirect(redirect_uri)


@app.route('/login/google/authorize')
def google():
    new_token = oauth.google.authorize_access_token()
    current_user.token = new_token
    current_user.save()
    return redirect(url_for('.index'))
```

First i ran into this error
```
Traceback (most recent call last):
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/nebularazer/test_app/gsuite/controller/contacts.py", line 78, in index
    log.info('scopes %s', current_user.granted_scopes)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/nebularazer/test_app/gsuite/models/user.py", line 78, in granted_scopes
    req = oauth.google.post('/oauth2/v2/tokeninfo', params=params)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/client/client.py", line 188, in post
    return self.request('POST', url, **kwargs)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/flask/client/oauth.py", line 181, in request
    method, url, token=token, **kwargs)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/client/client.py", line 170, in request
    return session.request(method, url, **kwargs)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/client/oauth2.py", line 306, in request
    self.refresh_token_url, auth=auth, **kwargs
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/client/oauth2.py", line 234, in refresh_token
    refresh_token=refresh_token, **kwargs
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/specs/rfc6749/parameters.py", line 107, in prepare_token_request
    return add_params_to_qs(body, params)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/common/urls.py", line 106, in add_params_to_qs
    return url_encode(qs)
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/common/urls.py", line 44, in url_encode
    encoded.append((to_bytes(k), to_bytes(v)))
  File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/common/encoding.py", line 24, in to_bytes
    return byte_type(x)
TypeError: 'str' object cannot be interpreted as an integer
```
I was able to get around this by adding the following to [this](https://github.com/lepture/authlib/blob/v0.6/authlib/common/encoding.py#L15)

``` python
def to_bytes(x, charset='utf-8', errors='strict'):
    if x is None:
        return None
    if isinstance(x, dict):  # <-- not sure if it is save to do so (the dict was the token)
        return None
    if isinstance(x, byte_type):
        return x
    if isinstance(x, unicode_type):
        return x.encode(charset, errors)
    if isinstance(x, (int, float)):
        return str(x).encode(charset, errors)
    return byte_type(x)
```

Then the refresh worked but `update_token` was never called.
I changed the following to make it work [here](https://github.com/lepture/authlib/blob/v0.6/authlib/flask/client/oauth.py#L142-L143)

``` python
if self.refresh_token_url:
    self.client_kwargs['token_updater'] = update_token
```

I am not sure if these changes break something else, but i hope this can be fixed anyways :)

**Comment by lepture** [comment]
This is a question rather than bug. Please ask it on StackOverflow. Just a quick hint:

The cause:

```
File "/home/nebularazer/test_app/.venv/lib/python3.6/site-packages/authlib/client/oauth2.py", line 234, in refresh_token
    refresh_token=refresh_token, **kwargs
```

In `refresh_token` method, there is a `prepare_token_request`. My guess is your `refresh_token` is not a valid token. Or there are other invalid parameters in `refresh_token` method. Please print all the parameters in `refresh_token`.

**Comment by nebularazer** [comment]
Thank you for looking at this.

This is was refresh token receives:
url: https://www.googleapis.com/oauth2/v4/token
refresh_token: None
body:
auth: <authlib.client.oauth2.OAuth2ClientAuth object at 0x7f234126a320>
headers: None
timeout: None
verify: True
proxies: None
kwargs: {'params': {'access_token': 'ya29.GlujBbIie...iyRlg', 'id_token': 'eyJhbGciOi...YQ'}}

This is was prepare_token_request receives:
body:
scope: email profile
refresh_token: 1/I9Z_I9kmQCOg....iFJIASS8xpuipbLdj
kwargs: {'params': {'access_token': 'ya29.GlujBbIie...iyRlg', 'id_token': 'eyJhbGciOi...YQ'}}

**Comment by lepture** [comment]
You see, your `kwargs` is invalid. Find out why there is a `params` in `kwargs`.

**Comment by nebularazer** [comment]
I found the issue in my side:
I had a method like this and used `params` as i am used to do with requests. My bad.
But the issue that `update_token` is not being fired still persists.

``` python
@property
def granted_scopes(self):
    if self.token is None:
        return []

    params = {
        'access_token': self.token['access_token'],
        'id_token': self.token['id_token']
    }
    req = oauth.google.post('/oauth2/v2/tokeninfo', params=params)
    if req.ok:
        data = req.json()
        scopes = data['scope'].split()
        return scopes
    else:
        log.info('failed to get scopes')
        return []
```

**Comment by nebularazer** [comment]
It is not called for me because `self.token_updater` is `None`.
I included a full example to show this, based on the docs. (These are working client secrets)
`env FLASK_APP=main.py FLASK_DEBUG=True flask run`

Tested with authlib0.6 and master.

https://github.com/lepture/authlib/blob/master/authlib/flask/client/oauth.py#L173
self.client_kwargs -> {'scope': 'email profile openid'}
...which results in token_updater not being set
https://github.com/lepture/authlib/blob/master/authlib/client/oauth2.py#L237
self.token_updater -> None

``` python
import logging
from time import time

from flask import Flask, jsonify, url_for, redirect, session, request
from authlib.flask.client import OAuth
from authlib.client.errors import OAuthException


logformat = '%(asctime)s [%(levelname)s] (%(name)s): %(message)s'
logging.basicConfig(level=logging.DEBUG, format=logformat)
log = logging.getLogger(__name__)

app = Flask(__name__)
app.config.update(
    SECRET_KEY='development',
    GOOGLE_CLIENT_ID='51052937567-0f6sm9dvnn8092pqlrub9mr6no9ln8i5.apps.googleusercontent.com',
    GOOGLE_CLIENT_SECRET='-Zmz39wboqL5-npjiRBXsCBg',
)


def fetch_token():
    log.info('fetching token')
    return session.get('token')


def update_token(token):
    log.info('updateing token')
    session['token'] = token
    return session['token']


oauth = OAuth(app)
oauth.register(
    'google',
    api_base_url='https://www.googleapis.com/',
    access_token_url='https://www.googleapis.com/oauth2/v4/token',
    authorize_url='https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent',
    refresh_token_url='https://www.googleapis.com/oauth2/v4/token',
    fetch_token=fetch_token,
    update_token=update_token,
    client_kwargs={
        'scope': 'email profile openid'
    }
)


@app.route('/')
def index():
    token = session.get('token')
    if token:
        token_is_expired = token['expires_at'] - time() < 0
    else:
        token_is_expired = True

    try:
        resp = oauth.google.get('/oauth2/v2/userinfo')
        profile = resp.json()
    except OAuthException as e:
        profile = e.message

    access_token = token.get('access_token')
    id_token = token.get('id_token')
    resp = oauth.google.post(f'/oauth2/v2/tokeninfo?access_token={access_token}&id_token={id_token}')
    tokeninfo = resp.json()

    return jsonify(login=url_for('login', _external=True),
                   expire_token=url_for('expire', _external=True),
                   delete_token=url_for('delete', _external=True),
                   profile=profile,
                   token=session.get('token'),
                   tokeninfo=tokeninfo,
                   token_is_expired=token_is_expired,
                   )


@app.route('/login')
def login():
    redirect_url = url_for('authorize', _external=True)
    return oauth.google.authorize_redirect(redirect_url)


@app.route('/authorize')
def authorize():
    token = oauth.google.authorize_access_token()
    session['token'] = token
    return redirect(url_for('index'))


@app.route('/expire')
def expire():
    log.info('setting expires_at...')
    token = session.get('token')
    if token:
        token['expires_at'] = time() - 10
        session['token'] = token
    return redirect(url_for('index'))


@app.route('/delete')
def delete():
    log.info('deleting token from session...')
    session.pop('token', None)
    return redirect(url_for('index'))
```
