### ISSUE TITLE
Missing Dependencies (httpx & itsdangerous)

### ISSUE THREAD

**Issue by exhuma** [lepture/authlib#618]
**Describe the bug**

When installing authlib for usage in a FastAPI/Starlette application, the `httpx` and `itsdangerous` dependencies are missing.

**Error Stacks**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspaces/oidc/env/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/workspaces/oidc/env/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/workspaces/oidc/env/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/workspaces/oidc/env/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/workspaces/oidc/env/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/workspaces/oidc/env/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/oidc/src/oidcdemo/app.py", line 1, in <module>
    from authlib.integrations.starlette_client import OAuth, OAuthError
  File "/workspaces/oidc/env/lib/python3.10/site-packages/authlib/integrations/starlette_client/__init__.py", line 5, in <module>
    from .apps import StarletteOAuth1App, StarletteOAuth2App
  File "/workspaces/oidc/env/lib/python3.10/site-packages/authlib/integrations/starlette_client/apps.py", line 7, in <module>
    from ..httpx_client import AsyncOAuth1Client, AsyncOAuth2Client
  File "/workspaces/oidc/env/lib/python3.10/site-packages/authlib/integrations/httpx_client/__init__.py", line 9, in <module>
    from .oauth1_client import OAuth1Auth, AsyncOAuth1Client, OAuth1Client
  File "/workspaces/oidc/env/lib/python3.10/site-packages/authlib/integrations/httpx_client/oauth1_client.py", line 2, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

**To Reproduce**

A minimal example to reproduce the behavior:

* Install `fastapi`
* Install `authlib`
* Implement an OpenID Connect login route
* Trigger the login route

**Expected behavior**

The application should make a HTTP request to the OIDC IDP.

**Environment:**

 - OS: `Linux 0dad33c0db66 5.15.90.2-microsoft-standard-WSL2 #1 SMP Fri Jun 2 00:45:15 UTC 2023 x86_64 GNU/Linux`
 - Python Version: Python 3.10.13
 - Authlib Version: 1.3.0

**Comment by exhuma** [comment]
Another missing dependency is `itsdangerous`. I updated the ticket accordingly.

**Comment by hudrazine** [comment]
@exhuma Hey, this Issue is neither a bug nor a missing issue, it is about installing dependencies.

authlib has optional dependencies on `requests` and `httpx`. These are required when using authlib in a FastAPI/Starlette application, but they are not automatically installed with the installation of authlib itself. They must be installed explicitly by the developer.

Similarly, `itsdangerous` is another optional dependency. It is required when using starlette’s SessionMiddleware, but it is not automatically installed with the installation of authlib or starlette itself. It must be installed explicitly by the developer.

**Comment by lepture** [comment]
@hudrazine has answered your question. Thanks.
