### ISSUE TITLE
save_request_token not defined

### ISSUE THREAD

**Issue by willgdjones** [lepture/authlib#95]
While integrating my Twitter backend I encountered this error:

```
Traceback (most recent call last)
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/loginpass/_flask.py", line 71, in login
return remote.authorize_redirect(redirect_uri, **params)
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/authlib/flask/client/oauth.py", line 235, in authorize_redirect
**kwargs)
File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python3.6/site-packages/authlib/client/client.py", line 116, in generate_authorize_redirect
save_request_token(token)
TypeError: 'NoneType' object is not callable
```

Dependences:
```
Name: loginpass
Version: 0.2

Name: Authlib
Version: 0.9
```

**Comment by willgdjones** [comment]
I followed the code, and I don't think that it is necessary. So I removed this line and it worked.

**Comment by lepture** [comment]
Not an issue in Authlib. You need a `cache` instance for OAuth 1. https://docs.authlib.org/en/latest/flask/client.html#oauth-1-request-token

Fixed in loginpass.
